name: prod

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git status
      - uses: actions/upload-artifact@v4
        with:
          path: .
          retention-days: 1
