name: prod

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches-ignore:
      - "!main"

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git status
